spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_service
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}
